inputs:
  source:
    description: “The site handle to screenshot”
    required: true
  command:
    description: "The wayback.py command to run"
    required: true

runs:
  using: "composite"
  steps:
    - id: save-page
      name: Save in Wayback Machine
      run: pipenv run python -m newshomepages.wayback ${{ inputs.command }} ${{ inputs.source }}
      shell: bash
